server:
  port: 9000
  servlet:
    context-path: /demo

justauth:
  enabled: true
  extend:
    enum-class: com.xkcoding.justauthspringbootstarterdemo.extend.AuthCustomSource
    config:
      UAP_DEV:
        request-class: com.xkcoding.justauthspringbootstarterdemo.extend.AuthUapDevRequest
        client-id: ZcELFz6XnHrVDy46
        client-secret: ac8e43e0db655acbc297220d37ecc3f57291de1614b312cf884a8cf97e5cf412
        redirect-uri: http://localhost:9000/demo/oauth/uap_dev/callback
#  type:
#    GOOGLE:
#      client-id: xxxxxx
#      client-secret: xxxxxxxx
#      redirect-uri: http://localhost:8443/oauth/google/callback
#      ignore-check-state: false
#      scopes:
#        - profile
#        - email
#        - openid
  cache:
    type: default
  #    prefix: 'demo::'
  #    timeout: 1h
#  http-config:
#    timeout: 30000
#    proxy:
#      GOOGLE:
#        type: HTTP
#        hostname: 127.0.0.1
#        port: 10080
#      MYGITLAB:
#        type: HTTP
#        hostname: 127.0.0.1
#        port: 10080

#spring:
#  redis:
#    host: localhost
#    # 连接超时时间（记得添加单位，Duration）
#    timeout: 10000ms
#    # Redis默认情况下有16个分片，这里配置具体使用的分片
#    # database: 0
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-wait: -1ms
#        # 连接池中的最大空闲连接 默认 8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认 0
#        min-idle: 0
#  cache:
#    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
#    type: redis
logging:
  level:
    com.xkcoding: debug